-- Run this in Supabase SQL Editor to complete owner <-> tenant chat system

-- Create messages table if not exists
create table if not exists public.owner_chat_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.owner_chats(id) on delete cascade,
  sender_role text not null check (sender_role in ('owner', 'tenant')),
  sender_email text,
  message text not null,
  created_at timestamp with time zone not null default now()
);

alter table public.owner_chat_messages enable row level security;

drop policy if exists "Authenticated users can read owner chat messages" on public.owner_chat_messages;
drop policy if exists "Authenticated users can create owner chat messages" on public.owner_chat_messages;

create policy "Authenticated users can read owner chat messages"
on public.owner_chat_messages
for select
to authenticated
using (true);

create policy "Authenticated users can create owner chat messages"
on public.owner_chat_messages
for insert
to authenticated
with check (true);

-- Add read status fields to owner_chats if not exists
alter table public.owner_chats
add column if not exists is_read_by_owner boolean not null default false,
add column if not exists is_read_by_tenant boolean not null default false;
