-- Run this in Supabase SQL Editor if owner_chats does not exist

create table if not exists public.owner_chats (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  contact_name text,
  contact_email text,
  listing_title text,
  last_message text,
  last_message_at timestamp with time zone not null default now(),
  status text not null default 'pendiente' check (status in ('abierto', 'pendiente', 'cerrado')),
  created_at timestamp with time zone not null default now()
);

alter table public.owner_chats enable row level security;

drop policy if exists "Authenticated users can read owner chats" on public.owner_chats;
drop policy if exists "Authenticated users can create owner chats" on public.owner_chats;
drop policy if exists "Authenticated users can update owner chats" on public.owner_chats;

create policy "Authenticated users can read owner chats"
on public.owner_chats
for select
to authenticated
using (true);

create policy "Authenticated users can create owner chats"
on public.owner_chats
for insert
to authenticated
with check (true);

create policy "Authenticated users can update owner chats"
on public.owner_chats
for update
to authenticated
using (true)
with check (true);
