-- Run this in Supabase SQL Editor

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  contract_type text not null check (contract_type in ('Venta', 'Alquiler')),
  property_type text not null check (property_type in ('Casa', 'Local', 'Apartamento')),
  neighborhood text not null,
  city text not null,
  description text,
  image_urls text[] not null default '{}',
  price numeric(12,2) not null check (price > 0),
  currency text not null check (currency in ('Lempiras', 'Dolares')),
  available boolean not null default true,
  created_at timestamp with time zone not null default now()
);

alter table public.properties add column if not exists available boolean not null default true;
alter table public.properties add column if not exists description text;
alter table public.properties add column if not exists image_urls text[] not null default '{}';

alter table public.properties enable row level security;

create policy if not exists "Authenticated users can create properties"
on public.properties
for insert
to authenticated
with check (true);

create policy if not exists "Authenticated users can read properties"
on public.properties
for select
to authenticated
using (true);

create policy if not exists "Authenticated users can update own properties"
on public.properties
for update
to authenticated
using (true)
with check (true);

-- Phone login index (maps phone to email for sign-in with password)
create table if not exists public.user_phone_login (
  email text primary key,
  phone_e164 text unique not null,
  created_at timestamp with time zone not null default now()
);

alter table public.user_phone_login enable row level security;

create policy if not exists "Allow insert phone login index"
on public.user_phone_login
for insert
to anon, authenticated
with check (true);

create policy if not exists "Allow update phone login index"
on public.user_phone_login
for update
to anon, authenticated
using (true)
with check (true);

create policy if not exists "Allow read phone login index"
on public.user_phone_login
for select
to anon, authenticated
using (true);
